### GET all posts
GET http://localhost:3000/api/posts/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJlbWFpbCI6ImhvbGEyQGdtYWlsLmNvbSIsImlhdCI6MTcyMjQyNTk2MH0.sSOxkN0vVXADz-ewBs3tWEFtQAQYKpnwgN3eAdnVlj0

### GET all posts
GET http://localhost:3000/api/posts/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJlbWFpbCI6ImhvbGEyQGdtYWlsLmNvbSIsImlhdCI6MTcyMjQyNTk2MH0.sSOxkN0vVXADz-ewBs3tWEFtQAQYKpnwgN3eAdnVlj0

### POST create post
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6ImhvbGEyQGdtYWlsLmNvbSIsImlhdCI6MTcyMjUwMTIyMH0.lorE77bCxzR6mOZtrxHVXKDjRGw3zBbrCq4SpEKJnn8

{
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

### GET post by id
GET http://localhost:3000/api/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJlbWFpbCI6ImhvbGEyQGdtYWlsLmNvbSIsImlhdCI6MTcyMjQyNTk2MH0.sSOxkN0vVXADz-ewBs3tWEFtQAQYKpnwgN3eAdnVlj0